import test from 'node:test';
import assert from 'node:assert/strict';
import {catalog,hughProfile,newProfile,makeTape,allAlbums} from '../lib/music.ts';
import {matchTrack} from '../lib/track-match.ts';
test('discovery excludes all known-loved artists, including names containing commas',()=>{const p=hughProfile();for(let round=0;round<4;round++){const t=makeTape(p,'discovery',20,[1987,1995],round);const favorites=p.favorites.split(';').map(x=>x.trim());const loved=allAlbums(p).filter(a=>p.ratings[a.id]==='love').map(a=>a.artist);for(const song of t.tracks){assert.ok(!favorites.includes(song.artist));assert.ok(!loved.includes(song.artist));assert.ok(song.year>=1987&&song.year<=1995);}assert.equal(new Set(t.tracks.map(s=>s.artist)).size,4);assert.equal(t.tracks.length,12);}});
test('memories come only from loved artists; passed records remain excluded',()=>{const p=hughProfile();p.ratings.fear='pass';const t=makeTape(p,'memories',20,[1960,2026]);for(const s of t.tracks){assert.notEqual(s.album,'fear');assert.ok(catalog.some(a=>a.artist===s.artist&&p.ratings[a.id]==='love'));}});
test('a new listener is not assigned Hugh’s loves',()=>{const p=newProfile('Another listener');assert.deepEqual(p.ratings,{});assert.equal(p.favorites,'');assert.throws(()=>makeTape(p,'memories',20,[1987,1995]),/Mark a few/);});
test('high adventure moves fuzzier and indie records into the first tape',()=>{const p=hughProfile();const near=makeTape(p,'discovery',0,[1987,1995]);const far=makeTape(p,'discovery',100,[1987,1995]);assert.notDeepEqual(near.tracks.map(x=>x.artist),far.tracks.map(x=>x.artist));assert.ok(far.tracks.some(x=>x.artist==='Dinosaur Jr.'));});
test('track matching rejects covers and live versions, prefers the original album',()=>{const t={title:'Blue',artist:'The Jayhawks',album:'Tomorrow the Green Grass',year:1995};const items=[{name:'Blue',uri:'cover',artists:[{name:'Another Artist'}],album:{name:t.album}},{name:'Blue - Live',uri:'live',artists:[{name:t.artist}],album:{name:'Live'}},{name:'Blue',uri:'compilation',artists:[{name:t.artist}],album:{name:'Best Of'}},{name:'Blue - 2011 Remaster',uri:'album',artists:[{name:t.artist}],album:{name:t.album}}];assert.equal(matchTrack(t,items).uri,'album');assert.equal(matchTrack(t,items.slice(0,2)),undefined);});
