import {z} from 'zod';
import {identity,db,body,fail,ApiError} from '@/lib/server';
import {accessToken,spotifyRequest,matchTrack,type SpotifyTrack} from '@/lib/spotify';
const track=z.object({title:z.string().min(1).max(300),artist:z.string().min(1).max(300),album:z.string().max(300),year:z.number()});
export async function POST(request:Request){let lock:string|null=null;try{const u=await identity(request);const {tape}=z.object({tape:z.object({id:z.string().min(1).max(100),title:z.string().min(1).max(200),tracks:z.array(track).min(1).max(60)})}).parse(await body(request));const exportKey=u.userId+':'+tape.id;const existing=await db().prepare('SELECT result FROM spotify_exports WHERE export_key = ?').bind(exportKey).first<{result:string|null}>();if(existing?.result)return Response.json(JSON.parse(existing.result));if(existing)throw new ApiError('This tape is already being exported. Please try again in a moment.',409);
 const token=await accessToken(u.userId);const claim=await db().prepare('INSERT OR IGNORE INTO spotify_exports (export_key, result, created_at) VALUES (?, NULL, ?)').bind(exportKey,new Date().toISOString()).run();if(!claim.meta.changes)throw new ApiError('This tape is already being exported.',409);lock=exportKey;
 const uris:string[]=[],missing:string[]=[];for(const t of tape.tracks){const q=new URLSearchParams({q:`track:${t.title} artist:${t.artist}`,type:'track',limit:'10'});const found=await spotifyRequest('/search?'+q,token) as {tracks?:{items:SpotifyTrack[]}};const match=matchTrack(t,found.tracks?.items||[]);if(match)uris.push(match.uri);else missing.push(t.artist+' — '+t.title);}if(!uris.length)throw new ApiError('None of these songs could be confidently matched on Spotify. Try the individual Listen links.');
 const playlist=await spotifyRequest('/me/playlists',token,'POST',{name:tape.title,public:false,description:'Made with Second Spin. Three invitations into each artist’s world.'}) as {id:string};const url='https://open.spotify.com/playlist/'+playlist.id;
 // Record the created playlist before adding tracks. Retrying never creates duplicate playlists.
 let result={url,added:0,missing,warning:'The playlist was created, but songs may not have been added. Open it in Spotify to check.'};await db().prepare('UPDATE spotify_exports SET result = ? WHERE export_key = ?').bind(JSON.stringify(result),exportKey).run();lock=null;
 try{await spotifyRequest('/playlists/'+playlist.id+'/items',token,'POST',{uris});result={url,added:uris.length,missing,warning:''};}catch{result={url,added:0,missing,warning:'Spotify created the playlist but could not confirm its songs. Open the playlist to check; use Download track list if you need to add them manually.'};}
 await db().prepare('UPDATE spotify_exports SET result = ? WHERE export_key = ?').bind(JSON.stringify(result),exportKey).run();return Response.json(result);
 }catch(e){if(lock)await db().prepare('DELETE FROM spotify_exports WHERE export_key = ? AND result IS NULL').bind(lock).run();return fail(e);}}
