'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Disc3,Headphones,CassetteTape,SlidersHorizontal,Plus,Bookmark,Check,RotateCcw,Heart,ExternalLink,BookOpen,Music2,Loader2,X,Download,Send} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {catalog,ratings,hughProfile,newProfile,allAlbums,makeTape,searchLink,tapeText,type Room,type Profile,type Album,type Tape,type Rating} from '@/lib/music';
import artwork from '@/lib/artwork.json';

const art=artwork as Record<string,{path:string;source:string}>;
async function api<T=unknown>(url:string,method='GET',data?:unknown){const r=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const j=await r.json() as {error?:string};if(!r.ok)throw Object.assign(new Error(j.error||'Please try again.'),{status:r.status});return j as T;}
function Cover({album,small=false}:{album:Album;small?:boolean}){const src=art[album.id]?.path;return src?<img className={small?'cover small':'cover'} src={src} alt={`${album.artist} — ${album.title} album cover`} loading="lazy"/>:<div className={small?'cover album-type small':'cover album-type'} style={{backgroundColor:album.color}}><span>{album.artist}</span><strong>{album.title}</strong><span>{album.year}</span></div>;}
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
function PanelTitle({n,title,children}:{n:string;title:string;children?:React.ReactNode}){return <div className="panel-title"><span className="equipment-label">SS—{n} <span>{title}</span></span>{children}</div>;}

export default function ListeningRoom(){
 const [room,setRoom]=useState<Room>({profiles:[],activeId:''}),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[saving,setSaving]=useState(false),[unsaved,setUnsaved]=useState(false);
 const [ai,setAi]=useState(false),[spotify,setSpotify]=useState({connected:false,configured:false}),[tab,setTab]=useState('listen'),[modal,setModal]=useState<'welcome'|'profile'|'settings'|null>(null),[detail,setDetail]=useState<Album|null>(null);
 const [name,setName]=useState(''),[mode,setMode]=useState<'discovery'|'memories'>('discovery'),[adventure,setAdventure]=useState(20),[era,setEra]=useState<[number,number]>([1987,1995]),[draft,setDraft]=useState<Tape|null>(null),[round,setRound]=useState(0),[selected,setSelected]=useState(0),[shelfFilter,setShelfFilter]=useState('all'),[query,setQuery]=useState('');
 const [storyDraft,setStoryDraft]=useState<Profile|null>(null),[message,setMessage]=useState(''),[thinking,setThinking]=useState(false),[exporting,setExporting]=useState(false),[clientId,setClientId]=useState('');
 const current=room.profiles.find(p=>p.id===room.activeId),fallback=useMemo(()=>hughProfile(),[]),p=current||fallback;
 const stateRef=useRef({room,revision,saving});stateRef.current={room,revision,saving};
 const albums=useMemo(()=>allAlbums(p),[p]),shelf=albums.filter(a=>(shelfFilter==='all'||(shelfFilter==='favorites'?['love','rediscovered'].includes(p.ratings[a.id]):shelfFilter==='new'?['new','familiar'].includes(p.ratings[a.id]):!p.ratings[a.id]))&&`${a.artist} ${a.title}`.toLowerCase().includes(query.toLowerCase()));
 const featured=['sundays','church','replacements','jayhawks'].map(id=>albums.find(a=>a.id===id)!).filter(Boolean);
 const tape=draft,activeTrack=tape?.tracks[selected],activeAlbum=activeTrack?albums.find(a=>a.artist===activeTrack.artist&&a.title===activeTrack.album):undefined;
 useEffect(()=>{load();const params=new URLSearchParams(location.search);if(params.has('spotify')){toast(params.get('spotify')==='connected'?'Spotify connected. Your mixtape is ready to export.':params.get('reason')||'Spotify connection was not completed.');history.replaceState({},'',location.pathname);}},[]);
 async function load(){setLoadError('');try{const j=await api<{room:Room;revision:number;aiEnabled:boolean}>('/api/room');setRoom(j.room);setRevision(j.revision);setAi(j.aiEnabled);setLoaded(true);if(!j.room.profiles.length)setModal('welcome');else{const profile=j.room.profiles.find((x:Profile)=>x.id===j.room.activeId)||j.room.profiles[0];try{setDraft(makeTape(profile,'discovery',20,[1987,1995]));}catch{}}const s=await api<{connected:boolean;configured:boolean}>('/api/spotify');setSpotify(s);}catch(e){setLoaded(true);setLoadError((e as Error).message);}}
 async function commit(next:Room){if(stateRef.current.saving)return false;setRoom(next);setSaving(true);setUnsaved(true);stateRef.current={...stateRef.current,room:next,saving:true};try{const j=await api<{revision:number}>('/api/room','PUT',{room:next,revision:stateRef.current.revision});setRevision(j.revision);stateRef.current.revision=j.revision;setUnsaved(false);return true;}catch(e){toast.error((e as Error).message);return false;}finally{setSaving(false);stateRef.current.saving=false;}}
 async function updateProfile(next:Profile){return commit({...stateRef.current.room,profiles:stateRef.current.room.profiles.map(x=>x.id===next.id?next:x)});}
 async function start(hugh=false){const profile=hugh?hughProfile():newProfile(name.trim()||'My');const next={profiles:[...room.profiles,profile],activeId:profile.id};if(await commit(next)){setModal(null);setStoryDraft(profile);setName('');if(!hugh)setTab('story');try{setDraft(makeTape(profile,'discovery',20,era));}catch{}toast.success(hugh?'Welcome back, Hugh.':'Your listening room is ready.');}}
 function generate(nextMode=mode,nextAdventure=adventure,nextEra=era,nextRound=round){try{setDraft(makeTape(p,nextMode,nextAdventure,nextEra,nextRound));setSelected(0);}catch(e){toast.error((e as Error).message);}}
 async function rate(a:Album,r:Rating|'unrated'){if(!current){setModal('welcome');return;}const nextRatings={...p.ratings};if(r==='unrated')delete nextRatings[a.id];else nextRatings[a.id]=r;if(await updateProfile({...p,ratings:nextRatings}))toast.success(r==='rediscovered'?'There it is. Back on your shelf.':`${a.artist}: ${ratings.find(x=>x.value===r)?.label||'Still a guess'}`);}
 async function saveTape(){if(!tape||!current)return;if(await updateProfile({...p,tapes:[tape,...p.tapes.filter(t=>t.id!==tape.id)]}))toast.success('Saved to your tape box.');}
 async function feedback(artist:string,value:'keep'|'again'|'pass'){if(!tape)return;const next={...tape,feedback:{...tape.feedback,[artist]:value}};setDraft(next);const match=albums.filter(a=>a.artist===artist);const newRatings={...p.ratings};match.forEach(a=>{newRatings[a.id]=value==='keep'?'love':value==='pass'?'pass':'familiar';});await updateProfile({...p,ratings:newRatings,tapes:p.tapes.some(t=>t.id===next.id)?p.tapes.map(t=>t.id===next.id?next:t):[next,...p.tapes]});toast.success(value==='keep'?'A new favorite for the shelf.':'Your next tape will remember that.');}
 async function exportTape(){if(!tape)return;if(!spotify.connected){setModal('settings');return;}setExporting(true);try{const j=await api<{url:string;added:number;missing:string[];warning?:string}>('/api/spotify/export','POST',{tape});const next={...tape,spotifyUrl:j.url};setDraft(next);await updateProfile({...p,tapes:p.tapes.some(t=>t.id===next.id)?p.tapes.map(t=>t.id===next.id?next:t):[next,...p.tapes]});if(j.warning)toast.warning(j.warning,{duration:20000});else toast.success(j.missing?.length?`Saved ${j.added} songs. ${j.missing.length} could not be matched.`:'Your private Spotify playlist is ready.');if(j.missing?.length)toast(j.missing.join(' · '),{duration:15000});}catch(e){toast.error((e as Error).message);}finally{setExporting(false);}}
 function downloadTape(){if(!tape)return;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([tapeText(tape)],{type:'text/plain'}));link.download='second-spin-mixtape.txt';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
 async function connect(){try{const j=await api<{url:string}>('/api/spotify/connect','POST',{clientId:clientId.trim(),redirectUri:location.origin+'/spotify/callback'});location.assign(j.url);}catch(e){toast.error((e as Error).message);}}
 async function chat(){if(!message.trim()||!current||thinking||saving)return;setThinking(true);const userMessage=message.trim();setMessage('');try{const j=await api<{message:string;albums:Album[]}>('/api/discover','POST',{profileId:p.id,message:userMessage});const latest=stateRef.current.room.profiles.find(x=>x.id===p.id)||p;const next={...latest,messages:[...latest.messages,{role:'user' as const,content:userMessage},{role:'assistant' as const,content:j.message}].slice(-60),albums:[...latest.albums,...j.albums.filter((a:Album)=>!albums.some(b=>b.artist.toLowerCase()===a.artist.toLowerCase()&&b.title.toLowerCase()===a.title.toLowerCase()))].slice(0,150)};if(await updateProfile(next))toast.success(j.albums.length?'New suggestions added to your shelf.':'Added to your musical story.');}catch(e){setMessage(userMessage);toast.error((e as Error).message);}finally{setThinking(false);}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'read_listening_room',description:'Read the active listener, confirmed favorites, and the staged mixtape. Does not change anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({listener:p.name,favorites:albums.filter(a=>['love','rediscovered'].includes(p.ratings[a.id])).map(a=>({artist:a.artist,album:a.title})),tape:draft})},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[p,albums,draft]);

 return <div className="app-shell"><Toaster theme="dark"/><header className="masthead"><a className="wordmark" href="/" aria-label="Second Spin home"><Disc3 size={29}/><span>SECOND<span className="accent-word">SPIN</span><small>YOUR PERSONAL LISTENING ROOM</small></span></a><div className="header-tools"><span className="save-state">{saving?'Saving…':unsaved?<button onClick={()=>commit(room)}>Retry save</button>:current?'Collection saved':''}</span>{current&&<Pick label="Listener" value={p.id} onChange={id=>{commit({...room,activeId:id});setDraft(null);setStoryDraft(null);}} items={room.profiles.map(x=>({value:x.id,label:x.name+"’s room"}))}/>}<button className="icon-button" aria-label="Add a listener" title="Add a listener" onClick={()=>setModal('profile')}><Plus size={20}/></button><button className="icon-button" aria-label="Connections and settings" title="Connections" onClick={()=>setModal('settings')}><SlidersHorizontal size={20}/></button></div></header>
 <Tabs value={tab} onValueChange={v=>{setTab(v);if(v==='story')setStoryDraft(p);}} className="workspace-tabs"><nav className="nav-strip"><TabsList variant="line"><TabsTrigger value="listen"><Headphones/>Listening room</TabsTrigger><TabsTrigger value="shelf"><Disc3/>Your record shelf</TabsTrigger><TabsTrigger value="story"><BookOpen/>Your story</TabsTrigger><TabsTrigger value="tapes"><CassetteTape/>Tape box <span className="counter">{p.tapes.length}</span></TabsTrigger></TabsList><span className="edition">PERSONAL EDITION / NO. 001</span></nav>
 {loadError&&<div className="notice error" role="alert">{loadError} <button onClick={load}>Try again</button> <a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in</a></div>}
 {!loaded&&<div className="loading-state" role="status"><Loader2 className="spin"/>Opening the listening room…</div>}
 <TabsContent value="listen"><div className="room-heading"><div><p className="eyebrow">A LITTLE FAMILIAR. A LITTLE UNEXPECTED.</p><h1>There’s more out there.</h1></div><p>{current?`${p.name}, let’s find your next old favorite.`:'The records you remember. The ones still waiting.'}</p></div>
 <div className="listening-layout"><div className="stereo-stack"><section className="component receiver"><PanelTitle n="01" title="MEMORY TUNER"><span className="hardware-note">STEREO / PERSONAL SELECTION</span></PanelTitle><div className="receiver-display"><div><span className="display-kicker">TUNED TO</span><div className="display-years">{era[0]}<span>—</span>{era[1]}</div></div><div className="display-place"><span>{p.place||'Your formative years'}</span><small>{mode==='discovery'?'MUSIC YOU MISSED':'RECORDS THAT MADE YOU'}</small></div></div><div className="tuner-range"><span>1960</span><Slider aria-label="Album release years" min={1960} max={2026} step={1} minStepsBetweenThumbs={1} value={era} onValueChange={v=>setEra(v as [number,number])} onValueCommit={v=>generate(mode,adventure,v as [number,number])}/><span>2026</span></div><div className="preset-row"><span className="mini-label">PRESETS</span>{[{name:'Teenage years',years:[p.born+13,p.born+20]},{name:'Parents’ records',years:[1960,1980]},{name:'The whole shelf',years:[1960,2026]}].map(x=><button className="hardware-button" key={x.name} onClick={()=>{const y=x.years.map(n=>Math.max(1960,Math.min(2026,n))) as [number,number];setEra(y);generate(mode,adventure,y);}}>{x.name}</button>)}</div></section>
 <section className="component decks"><PanelTitle n="02" title="DUAL MIXTAPE DECK"><span className="hardware-note">THREE SONGS / EACH ARTIST</span></PanelTitle><div className="deck-switches">{[{value:'memories' as const,letter:'A',name:'Old favorites',caption:'You know every word.'},{value:'discovery' as const,letter:'B',name:'The missing years',caption:'Meet the ones you missed.'}].map(x=><button key={x.value} className={'deck-choice '+(mode===x.value?'active':'')} aria-pressed={mode===x.value} onClick={()=>{setMode(x.value);setRound(0);generate(x.value,adventure,era,0);}}><span className="deck-letter">{x.letter}</span><span><strong>{x.name}</strong><small>{x.caption}</small></span><CassetteTape size={32}/></button>)}</div><div className="mix-controls"><div className="dial-copy"><span className="mini-label">DISCOVERY DISTANCE</span><strong>{adventure<35?'Close to home':adventure<70?'A little further':'Out on a limb'}</strong><span>From familiar melodies to stranger corners.</span></div><div className="distance-control"><div className="range-values"><span>COMFORT</span><b>{adventure}</b><span>ADVENTURE</span></div><Slider aria-label="Discovery distance" value={[adventure]} onValueChange={v=>setAdventure(v[0])} onValueCommit={v=>generate(mode,v[0],era)}/></div></div><div className="transport"><button className="primary-button" disabled={!current||saving} onClick={()=>{generate();setTab('listen');}}><CassetteTape size={19}/>Make my mixtape</button><button className="hardware-button" disabled={!current} onClick={()=>{setRound(round+1);generate(mode,adventure,era,round+1);}}><RotateCcw size={16}/>Different artists</button><span>HAND-PICKED STARTER CATALOG</span></div></section>
 <section className="discovery-shelf"><div className="section-heading"><div><p className="eyebrow">A FEW DOORS TO OPEN</p><h2>Your next discoveries</h2></div><button className="text-button" onClick={()=>{setShelfFilter('new');setTab('shelf');}}>Browse the shelf</button></div><div className="featured-grid">{featured.map(a=><button className="record-feature" key={a.id} onClick={()=>setDetail(a)}><Cover album={a}/><strong>{a.artist}</strong><span>{a.title}</span><small>{a.year} · {p.ratings[a.id]==='love'?'A new favorite':'Three songs to start'}</small></button>)}</div></section></div>
 <aside className="liner-panel"><div className="section-heading"><span className="eyebrow">ON THE TAPE</span><CassetteTape size={23}/></div>{tape?<><div className="tape-heading"><span className="tape-number">{mode==='discovery'?'B':'A'} / {String(tape.tracks.length).padStart(2,'0')} TRACKS</span><input aria-label="Mixtape title" value={tape.title} maxLength={200} onChange={e=>setDraft({...tape,title:e.target.value})}/><p>{tape.note}</p></div><div className="tape-actions"><button className="primary-button spotify" disabled={exporting||saving} onClick={exportTape}>{exporting?<Loader2 className="spin" size={16}/>:<ExternalLink size={16}/>}Save to Spotify</button><button className="icon-button" aria-label="Save mixtape to tape box" title="Save to tape box" disabled={saving} onClick={saveTape}>{p.tapes.some(t=>t.id===tape.id)?<Check size={19}/>:<Bookmark size={19}/>}</button><button className="icon-button" aria-label="Download track list" title="Download track list" onClick={downloadTape}><Download size={18}/></button></div>{tape.spotifyUrl&&<a className="playlist-link" href={tape.spotifyUrl} target="_blank" rel="noreferrer">Open your Spotify playlist</a>}<ol className="track-list">{tape.tracks.map((t,i)=><li key={i} className={selected===i?'selected':''}><button onClick={()=>setSelected(i)} className="track-select"><span className="track-number">{String(i+1).padStart(2,'0')}</span><span><strong>{t.title}</strong><small>{t.artist}</small></span></button><a href={searchLink(t)} target="_blank" rel="noreferrer" aria-label={`Find ${t.title} by ${t.artist} on Spotify`} title="Find in Spotify"><ExternalLink size={15}/></a></li>)}</ol>{activeTrack&&<div className="listening-note"><div className="note-heading">{activeAlbum&&<Cover album={activeAlbum} small/>}<div><span className="mini-label">WHY THIS ONE</span><strong>{activeTrack.artist}</strong></div></div><p>{activeTrack.note}</p><a href={searchLink(activeTrack)} target="_blank" rel="noreferrer" className="text-button">Listen in Spotify <ExternalLink size={13}/></a><div className="feedback"><span>After a listen…</span><div>{[{v:'keep' as const,label:'Keep exploring',icon:Heart},{v:'again' as const,label:'Another try',icon:RotateCcw},{v:'pass' as const,label:'Not for me',icon:X}].map(x=><button disabled={saving||!current} aria-pressed={tape.feedback[activeTrack.artist]===x.v} key={x.v} onClick={()=>feedback(activeTrack.artist,x.v)}><x.icon size={14}/>{x.label}</button>)}</div></div></div>}</>:<div className="empty-tape"><CassetteTape size={46}/><h2>A blank tape. A good beginning.</h2><p>Choose your years and make a mixtape.</p><button className="primary-button" onClick={()=>current?generate():setModal('welcome')}>{current?'Make my mixtape':'Choose a collection'}</button></div>}</aside></div></TabsContent>
 <TabsContent value="shelf"><div className="room-heading"><div><p className="eyebrow">THE RECORDS THAT MADE YOU</p><h1>Your record shelf.</h1></div><p>A favorite, a rediscovery, or a door you haven’t opened.</p></div><div className="shelf-tools"><input aria-label="Search albums and artists" placeholder="Find an artist or album…" value={query} onChange={e=>setQuery(e.target.value)}/><Pick label="Filter the record shelf" value={shelfFilter} onChange={setShelfFilter} items={[{value:'all',label:'All records'},{value:'favorites',label:'Loved & rediscovered'},{value:'new',label:'To explore'},{value:'unrated',label:'Still a guess'}]}/><span>{shelf.length} records</span></div><div className="album-grid">{shelf.map(a=><article className="album-card" key={a.id}><button className="album-open" onClick={()=>setDetail(a)}><Cover album={a}/><span className="album-year">{a.year}</span><h2>{a.title}</h2><p>{a.artist}</p></button><Pick label={`Your connection to ${a.title}`} value={p.ratings[a.id]||'unrated'} onChange={v=>rate(a,v as Rating)} items={[{value:'unrated',label:'Still a guess'},...ratings]}/></article>)}</div>{!shelf.length&&<div className="empty-tape"><Disc3 size={38}/><h2>Room for another record.</h2><p>Try another filter, or add suggestions through Your story.</p></div>}</TabsContent>
 <TabsContent value="story"><div className="room-heading"><div><p className="eyebrow">EVERY COLLECTION STARTS SOMEWHERE</p><h1>What did your world sound like?</h1></div></div><div className="story-layout"><form className="story-form" onSubmit={async e=>{e.preventDefault();if(storyDraft&&await updateProfile(storyDraft))toast.success('Your story is saved.');}}><h2>The person behind the records</h2><label>Your name<input required maxLength={80} value={storyDraft?.name??p.name} onChange={e=>setStoryDraft({...storyDraft||p,name:e.target.value})}/></label><div className="form-pair"><label>Year you were born<input type="number" min={1900} max={2020} value={storyDraft?.born??p.born} onChange={e=>setStoryDraft({...storyDraft||p,born:Number(e.target.value)})}/></label><label>Where you grew up<input maxLength={500} placeholder="A town, a country, a scene…" value={storyDraft?.place??p.place} onChange={e=>setStoryDraft({...storyDraft||p,place:e.target.value})}/></label></div><label>Artists you already love<textarea maxLength={3000} rows={3} placeholder="Separate names with a semicolon" value={storyDraft?.favorites??p.favorites} onChange={e=>setStoryDraft({...storyDraft||p,favorites:e.target.value})}/></label><label>The memories attached to the music<textarea maxLength={12000} rows={7} placeholder="Your first car. A borrowed tape. Your parents’ records. A tiny venue…" value={storyDraft?.story??p.story} onChange={e=>setStoryDraft({...storyDraft||p,story:e.target.value})}/></label><button className="primary-button" disabled={!current||saving} type="submit"><Bookmark size={17}/>Save my story</button></form><section className="conversation"><div className="section-heading"><div><span className="eyebrow">THE RECORD-STORE CONVERSATION</span><h2>Let’s remember.</h2></div><Music2/></div>{!ai&&<div className="notice">The personal conversation needs an OpenAI connection. For now, explore the starter shelf and save your memories here. <button onClick={()=>setModal('settings')}>Connection details</button></div>}<div className="messages"><div className="assistant-message">Tell me about three records you played from beginning to end. What was happening in your life when you found them?</div>{p.messages.map((m,i)=><div className={m.role+'-message'} key={i}>{m.content}</div>)}{thinking&&<div className="assistant-message"><Loader2 className="spin" size={17}/>Looking through the crates…</div>}</div><form onSubmit={e=>{e.preventDefault();chat();}} className="message-form"><textarea aria-label="Tell us a music memory" placeholder="I remember driving around listening to…" value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} rows={3}/><button aria-label="Send memory" className="primary-button" disabled={!ai||thinking||saving||!current||!message.trim()}><Send size={18}/></button></form><small className="subtle">Suggestions are guesses. Your corrections make the collection yours.</small></section></div></TabsContent>
 <TabsContent value="tapes"><div className="room-heading"><div><p className="eyebrow">KEEP THE GOOD ONES</p><h1>Your tape box.</h1></div><p>{p.tapes.length} mixtapes worth another spin.</p></div><div className="tape-grid">{p.tapes.map(t=><button className="saved-tape" key={t.id} onClick={()=>{setDraft(t);setMode(t.mode);setSelected(0);setTab('listen');}}><span className="tape-number">{t.mode==='discovery'?'SIDE B · DISCOVERY':'SIDE A · MEMORIES'}</span><CassetteTape size={36}/><h2>{t.title}</h2><p>{[...new Set(t.tracks.map(x=>x.artist))].join(' · ')}</p><small>{t.tracks.length} tracks · {new Date(t.createdAt).toLocaleDateString()}</small></button>)}</div>{!p.tapes.length&&<div className="empty-tape"><CassetteTape size={48}/><h2>Your first tape is waiting.</h2><p>Save a mix from the listening room and it will live here.</p><button className="primary-button" onClick={()=>setTab('listen')}>Back to the stereo</button></div>}</TabsContent></Tabs>
 <footer><span>SECOND SPIN <span className="footer-separator">/</span> MADE FOR THE JOY OF LISTENING</span><span>Artwork belongs to its respective owners. <a href="/art/sources.json" target="_blank" rel="noreferrer">Sources</a></span></footer>
 <Dialog open={modal==='welcome'||modal==='profile'} onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent className="room-dialog"><DialogTitle>{modal==='welcome'?'Whose records are we looking for?':'A listening room of your own.'}</DialogTitle><DialogDescription>Each listener has their own story, shelf, and mixtapes.</DialogDescription>{modal==='welcome'&&<button className="welcome-hugh" disabled={saving||!!loadError} onClick={()=>start(true)}><div className="welcome-covers">{['fear','fun-games','blind-melon'].map(id=><Cover key={id} album={catalog.find(a=>a.id===id)!}/>)}</div><strong>Open Hugh’s collection</strong><span>North Carolina · 1975 · the story so far</span></button>}<label>Your name<input autoComplete="given-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Shay, or someone new…" maxLength={80}/></label><button className="primary-button" disabled={!name.trim()||saving||!!loadError} onClick={()=>start(false)}>Start my own collection</button></DialogContent></Dialog>
 <Dialog open={modal==='settings'} onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent className="room-dialog"><DialogTitle>Connect the listening room.</DialogTitle><DialogDescription>Your collection stays private. Music plays in Spotify.</DialogDescription><div className="connection-card"><h3>Spotify <span>{spotify.connected?'Connected':'Not connected'}</span></h3>{spotify.connected?<><p>Ready to create private playlists from your mixtapes.</p><button className="hardware-button" onClick={async()=>{try{await api('/api/spotify','DELETE');setSpotify({...spotify,connected:false});toast.success('Spotify disconnected.');}catch(e){toast.error((e as Error).message);}}}>Disconnect Spotify</button></>:<><p>The owner needs a Spotify developer app. Add this exact callback address to its settings, then connect your account.</p><code>{typeof location!=='undefined'?location.origin:''}/spotify/callback</code><a href="https://developer.spotify.com/dashboard" target="_blank" rel="noreferrer" className="text-button">Open Spotify developer settings <ExternalLink size={13}/></a>{!spotify.configured&&<label>Spotify Client ID<input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="Public Client ID, not a client secret"/></label>}<button className="primary-button" onClick={connect} disabled={!spotify.configured&&!clientId.trim()}>Connect Spotify</button><p className="subtle">Add each tester in your Spotify app’s Users and Access list. Up to five authenticated users in development mode.</p></>}</div><div className="connection-card"><h3>Personal conversation <span>{ai?'Ready':'Setup needed'}</span></h3><p>{ai?'Your own words guide new suggestions. Spotify account data is never sent to the model.':'The owner can connect OpenAI Developers in ChatGPT to configure the conversation securely. The starter shelf, mixtapes, and saved memories work without it.'}</p></div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="room-dialog record-dialog">{detail&&<><div className="record-detail-top"><Cover album={detail}/><div><p className="eyebrow">{detail.year}</p><DialogTitle>{detail.title}</DialogTitle><DialogDescription>{detail.artist}</DialogDescription></div></div><p>{detail.note}</p><h3>Three songs to start</h3>{detail.tracks.map(t=><a className="detail-track" key={t.title} href={searchLink(t)} target="_blank" rel="noreferrer"><span>{t.title}</span><ExternalLink size={16}/></a>)}<Pick label="Your connection to this album" value={p.ratings[detail.id]||'unrated'} onChange={v=>rate(detail,v as Rating)} items={[{value:'unrated',label:'Still a guess'},...ratings]}/>{art[detail.id]&&<a className="subtle" href={art[detail.id].source} target="_blank" rel="noreferrer">Album artwork source</a>}</>}</DialogContent></Dialog></div>;
}
