import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {db,identity,fail,body,ApiError} from '@/lib/server';
const track=z.object({title:z.string().max(300),artist:z.string().max(300),album:z.string().max(300),year:z.number(),note:z.string().max(2000).optional()});
const album=z.object({id:z.string().max(200),artist:z.string().max(300),title:z.string().max(300),year:z.number(),tags:z.array(z.string().max(80)).max(20),color:z.string().max(30),note:z.string().max(2000),tracks:z.array(track).max(20),art:z.string().max(1000).optional(),source:z.string().max(1000).optional()});
const profile=z.object({id:z.string().max(100),name:z.string().min(1).max(80),born:z.number().min(1900).max(2020),place:z.string().max(500),favorites:z.string().max(3000),story:z.string().max(12000),ratings:z.record(z.enum(['love','rediscovered','familiar','new','pass'])),albums:z.array(album).max(150),messages:z.array(z.object({role:z.enum(['user','assistant']),content:z.string().max(12000)})).max(60),tapes:z.array(z.object({id:z.string().max(100),title:z.string().max(200),createdAt:z.string(),mode:z.enum(['discovery','memories']),tracks:z.array(track).max(60),note:z.string().max(2000),spotifyUrl:z.string().url().refine(v=>v.startsWith('https://open.spotify.com/playlist/')).optional(),feedback:z.record(z.enum(['keep','again','pass']))})).max(100)});
const schema=z.object({revision:z.number().int().min(0),room:z.object({profiles:z.array(profile).max(20),activeId:z.string().max(100)})});
export async function GET(){try{const user=await identity();let row=await db().prepare('SELECT document, revision FROM rooms WHERE owner_id = ?').bind(user.userId).first<{document:string;revision:number}>();if(!row){await db().prepare('INSERT OR IGNORE INTO rooms (owner_id, document, revision, updated_at) VALUES (?, ?, 0, ?)').bind(user.userId,JSON.stringify({profiles:[],activeId:''}),new Date().toISOString()).run();row=await db().prepare('SELECT document, revision FROM rooms WHERE owner_id = ?').bind(user.userId).first<{document:string;revision:number}>();}return Response.json({room:JSON.parse(row!.document),revision:row!.revision,aiEnabled:!!env.OPENAI_API_KEY,displayName:user.fullName||'',spotifyConfigured:!!env.SPOTIFY_CLIENT_ID});}catch(e){return fail(e);}}
export async function PUT(request:Request){try{const user=await identity(request);const checked=schema.safeParse(await body(request));if(!checked.success)throw new ApiError('Please check your collection details before saving.');const {room,revision}=checked.data;if(room.profiles.length&&!room.profiles.some(p=>p.id===room.activeId))throw new ApiError('Choose an existing listener.');const result=await db().prepare('UPDATE rooms SET document = ?, revision = revision + 1, updated_at = ? WHERE owner_id = ? AND revision = ?').bind(JSON.stringify(room),new Date().toISOString(),user.userId,revision).run();if(!result.meta.changes)throw new ApiError('This room changed in another tab. Reload before saving; copy any new notes first.',409);return Response.json({revision:revision+1});}catch(e){return fail(e);}}
