export type Rating = 'love' | 'rediscovered' | 'familiar' | 'new' | 'pass';
export type Track = { title:string; artist:string; album:string; year:number; note?:string };
export type Album = { id:string; artist:string; title:string; year:number; tags:string[]; color:string; note:string; tracks:Track[]; art?:string; source?:string };
export type Tape = { id:string; title:string; createdAt:string; mode:'discovery'|'memories'; tracks:Track[]; note:string; spotifyUrl?:string; feedback:Record<string,'keep'|'again'|'pass'> };
export type Profile = { id:string; name:string; born:number; place:string; favorites:string; story:string; ratings:Record<string,Rating>; albums:Album[]; tapes:Tape[]; messages:{role:'user'|'assistant';content:string}[] };
export type Room = { profiles:Profile[]; activeId:string };
const a=(id:string,artist:string,title:string,year:number,tags:string[],color:string,note:string,names:string[]):Album=>({id,artist,title,year,tags,color,note,tracks:names.map(name=>({title:name,artist,album:title,year}))});
export const catalog:Album[]=[
 a('fear','Toad the Wet Sprocket','fear',1991,['jangle','folk','melodic'],'#967858','Gentle melodies with a restless undercurrent. Start here for Toad’s folk-rock side.',['Walk on the Ocean','Nightingale Song','All I Want']),
 a('fun-games','The Connells','Fun & Games',1989,['jangle','southern','melodic'],'#a35d4e','Raleigh guitar pop: jangling melodies with just enough melancholy.',['Something to Say','Fun & Games','Hey Wow']),
 a('one-simple-word','The Connells','One Simple Word',1990,['jangle','southern','melodic'],'#6687aa','A fuller, harder-edged companion to Fun & Games.',['Stone Cold Yesterday','Get a Gun','One Simple Word']),
 a('ten','Pearl Jam','Ten',1991,['grunge','heavy','melodic'],'#ae4c70','Expansive guitar rock, with quiet moments as memorable as its anthems.',['Alive','Black','Release']),
 a('nevermind','Nirvana','Nevermind',1991,['grunge','heavy','punk'],'#36869e','A record whose next song arrives in your head before it starts.',['Come as You Are','Drain You','Lounge Act']),
 a('blood-sugar','Red Hot Chili Peppers','Blood Sugar Sex Magik',1991,['funk','heavy','melodic'],'#be5356','Funk, enormous guitars, and a whole world inside one album.',['Breaking the Girl','Under the Bridge','I Could Have Lied']),
 a('blind-melon','Blind Melon','Blind Melon',1992,['folk','southern','melodic'],'#bdad6d','Acoustic warmth and twisting, rootsy guitars beyond the familiar single.',['Change','Tones of Home','Sleepyhouse']),
 a('august','Counting Crows','August and Everything After',1993,['folk','melodic','southern'],'#9c7642','Late-night storytelling with plenty to discover beyond the singles.',['Anna Begins','Sullivan Street','A Murder of One']),
 a('gin-blossoms','Gin Blossoms','New Miserable Experience',1992,['jangle','melodic','southern'],'#8995a2','Bright guitars and bruised feelings, from the opening track onward.',['Lost Horizons','Until I Fall Away','Found Out About You']),
 a('sister-sweetly','Big Head Todd and the Monsters','Sister Sweetly',1993,['blues','southern','melodic'],'#8b614d','Bluesy, unhurried guitar rock with a quiet emotional pull.',['Bittersweet','Circle','Broken Hearted Savior']),
 a('lemonheads','The Lemonheads','It’s a Shame About Ray',1992,['jangle','folk','punk'],'#81a394','Short, intimate songs that invite another listen.',['Confetti','My Drug Buddy','Rudderless']),
 a('maniacs','10,000 Maniacs','In My Tribe',1987,['jangle','folk','melodic'],'#c0a970','Literary folk rock and Natalie Merchant’s unmistakable voice.',['Don’t Talk','Like the Weather','What’s the Matter Here?']),
 a('indigo','Indigo Girls','Indigo Girls',1989,['folk','harmonies','melodic'],'#72917b','Two voices, acoustic guitars, and emotional weight.',['Closer to Fine','Kid Fears','Prince of Darkness']),
 a('soul-asylum','Soul Asylum','Grave Dancers Union',1992,['melodic','heavy','jangle'],'#b9885f','Ragged guitars with a tender heart.',['Somebody to Shove','Black Gold','Runaway Train']),
 a('jump','Jump, Little Children','The Licorice Tea Demos',1995,['folk','southern','jangle'],'#949867','The Charleston band that came back in a flash of recognition.',['Quiet','Dancing Virginia','Smiling Down']),
 a('violent-femmes','Violent Femmes','Violent Femmes',1983,['folk','punk','jangle'],'#b4a584','Acoustic instruments with the nervous energy of punk.',['Blister in the Sun','Kiss Off','Add It Up']),
 a('sundays','The Sundays','Reading, Writing and Arithmetic',1990,['jangle','folk','melodic'],'#aab4a5','Shimmering guitars and a clear, floating voice: an invitation from the gentler side of Toad.',['Here’s Where the Story Ends','Can’t Be Sure','You’re Not the Only One I Know']),
 a('church','The Church','Starfish',1988,['jangle','psychedelic','melodic'],'#b09062','A spacious, atmospheric step out from familiar guitar rock.',['Under the Milky Way','Reptile','North, South, East and West']),
 a('replacements','The Replacements','Pleased to Meet Me',1987,['jangle','punk','melodic'],'#a6a4c1','Loose, bruised, and tuneful; a natural first stop for a Soul Asylum fan.',['Can’t Hardly Wait','Alex Chilton','Skyway']),
 a('dinosaur','Dinosaur Jr.','Where You Been',1993,['heavy','indie','melodic'],'#b7745f','There are memorable melodies inside all that guitar fuzz.',['Start Choppin','Out There','Goin Home']),
 a('pavement','Pavement','Crooked Rain, Crooked Rain',1994,['indie','jangle','punk'],'#d0a379','An approachable opening into their loose, sideways indie rock.',['Cut Your Hair','Gold Soundz','Range Life']),
 a('superchunk','Superchunk','Foolish',1994,['indie','punk','southern'],'#b87786','A louder North Carolina detour, with melody under the abrasion.',['Driveway to Driveway','Like a Fool','Water Wings']),
 a('jayhawks','The Jayhawks','Tomorrow the Green Grass',1995,['folk','harmonies','southern'],'#6397b0','A bridge from the Eagles’ harmonies to the rootsier side of Counting Crows.',['Blue','I’d Run Away','Miss Williams’ Guitar']),
 a('rem','R.E.M.','Green',1988,['jangle','southern','melodic'],'#bc8d35','A bridge between R.E.M.’s jangling roots and bigger, stranger possibilities.',['Orange Crush','You Are the Everything','World Leader Pretend']),
 a('u2','U2','The Joshua Tree',1987,['melodic','atmospheric','rock'],'#716d5e','Open spaces, ringing guitars, and a second side worth revisiting.',['Where the Streets Have No Name','Running to Stand Still','One Tree Hill']),
 a('soundgarden','Soundgarden','Badmotorfinger',1991,['heavy','grunge','psychedelic'],'#b45230','For the louder side of the collection.',['Outshined','Rusty Cage','Slaves & Bulldozers']),
 a('eagles','Eagles','Their Greatest Hits 1971–1975',1976,['harmonies','folk','southern'],'#779cac','A possible edition of the Eagles heard at home; confirm the record.',['Take It Easy','Lyin’ Eyes','Take It to the Limit']),
 a('kenny','Kenny Rogers','Greatest Hits',1980,['country','folk','melodic'],'#b67960','Storytelling from the family record collection; the exact album is a guess.',['The Gambler','Lady','Lucille']),
 a('simon','Simon & Garfunkel','Bridge Over Troubled Water',1970,['folk','harmonies','melodic'],'#799ea3','The voices came from home. Is this the particular record?',['The Boxer','The Only Living Boy in New York','Cecilia']),
 a('fourtops','Four Tops','Reach Out',1967,['soul','harmonies','melodic'],'#796599','An album to check against the Four Tops remembered from childhood.',['Reach Out I’ll Be There','Bernadette','Standing in the Shadows of Love']),
 a('orbison','Roy Orbison','Mystery Girl',1989,['melodic','rock','harmonies'],'#8a8398','A possible later bridge from the Roy Orbison heard at home.',['You Got It','She’s a Mystery to Me','California Blue']),
 a('zeppelin','Led Zeppelin','Led Zeppelin IV',1971,['heavy','blues','folk'],'#979070','A discovery made independently; this particular album is still a guess.',['Black Dog','Going to California','When the Levee Breaks']),
 a('stones','The Rolling Stones','Sticky Fingers',1971,['blues','southern','rock'],'#94908c','One possible starting point for the Stones discovered independently.',['Wild Horses','Can’t You Hear Me Knocking','Moonlight Mile']),
 a('croce','Jim Croce','You Don’t Mess Around with Jim',1972,['folk','melodic','country'],'#b49a78','Warm storytelling, fingerpicked guitar, and songs that stay with you.',['Operator (That’s Not the Way It Feels)','Time in a Bottle','You Don’t Mess Around with Jim']),
 a('catstevens','Cat Stevens','Tea for the Tillerman',1970,['folk','melodic','harmonies'],'#8d9f71','Acoustic music with an earnest, searching heart.',['Wild World','Father and Son','Where Do the Children Play?']),
 a('samcooke','Sam Cooke','The Best of Sam Cooke',1962,['soul','melodic','harmonies'],'#8096a6','A voice to explore if the Four Tops and Roy Orbison move you.',['You Send Me','Wonderful World','Chain Gang']),
 a('fleetwood','Fleetwood Mac','Rumours',1977,['harmonies','melodic','rock'],'#ac977c','Interlocking voices and songs with complicated feelings.',['Dreams','Never Going Back Again','The Chain']),
];
export const ratings:{value:Rating;label:string}[]=[{value:'love',label:'Loved it'},{value:'rediscovered',label:'Forgot about it!'},{value:'familiar',label:'Know the name'},{value:'new',label:'New to me'},{value:'pass',label:'Not for me'}];
export function newProfile(name:string):Profile{return {id:crypto.randomUUID(),name,born:1975,place:'',favorites:'',story:'',ratings:{},albums:[],tapes:[],messages:[]};}
export function hughProfile():Profile{const p=newProfile('Hugh');p.place='North Carolina';p.favorites='Toad the Wet Sprocket; The Connells; Counting Crows; Gin Blossoms; Blind Melon; Pearl Jam; Nirvana; Big Head Todd and the Monsters; Jump, Little Children; R.E.M.; U2; Soundgarden; Eagles; Kenny Rogers; Four Tops; Simon & Garfunkel; Roy Orbison; Led Zeppelin; The Rolling Stones';p.story='Born in 1975. Skateboarding, record-store discoveries, driving around as a teenager. Parents played Eagles, Kenny Rogers, Four Tops, Simon & Garfunkel and Roy Orbison. Discovered Led Zeppelin and the Rolling Stones independently. Bought Blind Melon for its cover and saw them in a tiny venue. Toad’s fear was perhaps the favorite album. The Connells: Fun & Games and One Simple Word. R.E.M. was liked, but not an obsession. Big Head Todd was also loved.';for(const id of ['fear','fun-games','one-simple-word','ten','nevermind','blood-sugar','blind-melon','august','gin-blossoms','sister-sweetly','lemonheads','maniacs','indigo','soul-asylum','violent-femmes'])p.ratings[id]='love';for(const id of ['sundays','church','pavement','superchunk','jayhawks'])p.ratings[id]='new';for(const id of ['dinosaur','replacements','jump','rem','u2','soundgarden','eagles','kenny','simon','fourtops','orbison','zeppelin','stones'])p.ratings[id]='familiar';return p;}
export function allAlbums(p:Profile){return [...catalog,...p.albums.filter(a=>!catalog.some(c=>c.id===a.id))];}
export function makeTape(p:Profile,mode:'discovery'|'memories',adventure:number,era:[number,number],round=0):Tape{
 const albums=allAlbums(p),loved=albums.filter(a=>['love','rediscovered'].includes(p.ratings[a.id]));
 const lovedArtists=new Set(loved.map(a=>a.artist.toLowerCase()));
 const familiar=new Set(p.favorites.split(p.favorites.includes(';')?/[;\n]/:/[,\n]/).map(x=>x.trim().toLowerCase()).filter(Boolean));
 const tags=new Map<string,number>();loved.forEach(a=>a.tags.forEach(t=>tags.set(t,(tags.get(t)||0)+1)));
 const candidates=albums.filter(a=>a.year>=era[0]&&a.year<=era[1]&&p.ratings[a.id]!=='pass'&&(mode==='memories'?lovedArtists.has(a.artist.toLowerCase()):!lovedArtists.has(a.artist.toLowerCase())&&!familiar.has(a.artist.toLowerCase())));
 const score=(a:Album)=>a.tags.reduce((n,t)=>n+(tags.get(t)||0),0)*(1-adventure/140)+(a.tags.includes('indie')||a.tags.includes('heavy')?adventure*.32:0)+(p.ratings[a.id]==='new'?3:0);
 const ordered=candidates.sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id));
 const selected:Album[]=[],seen=new Set<string>();for(let i=0;i<ordered.length;i++){const a=ordered[(i+round*4)%ordered.length];if(!seen.has(a.artist)){selected.push(a);seen.add(a.artist);}if(selected.length===4)break;}
 if(!selected.length)throw new Error(mode==='memories'?'Mark a few albums “Loved it” or widen the year range first.':'No unfamiliar artists remain in this range. Widen the years or add more suggestions in Your story.');
 const tracks=[0,1,2].flatMap(i=>selected.flatMap(a=>a.tracks[i]?[{...a.tracks[i],note:a.note}]:[]));
 return {id:crypto.randomUUID(),title:`${p.name}’s ${mode==='discovery'?'missing years':'old favorites'} · Vol. ${p.tapes.filter(t=>t.mode===mode).length+1}`,createdAt:new Date().toISOString(),mode,tracks,note:mode==='discovery'?'Three invitations into each artist’s world. Listen in order, then tell us what stays.':'The songs attached to your own memories. Familiar company for another drive.',feedback:{}};
}
export function searchLink(t:Track){return `https://open.spotify.com/search/${encodeURIComponent(t.artist+' '+t.title)}`;}
export function tapeText(t:Tape){return `${t.title}\n${t.note}\n\n${t.tracks.map((s,i)=>`${i+1}. ${s.artist} — ${s.title} (${s.album}, ${s.year})`).join('\n')}`;}
