import {env} from 'cloudflare:workers';
import {db,ApiError} from './server';
export const cookieName='__Host-secondspin-oauth';
export function base64(bytes:Uint8Array){let s='';for(const byte of bytes)s+=String.fromCharCode(byte);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function unbase64(s:string){const value=s.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(value+'='.repeat((4-value.length%4)%4)),c=>c.charCodeAt(0));}
async function key(){if(!env.SPOTIFY_TOKEN_KEY)throw new ApiError('Spotify needs one final server setup step. Please contact the owner.',503);return crypto.subtle.importKey('raw',unbase64(env.SPOTIFY_TOKEN_KEY),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function seal(value:unknown,owner:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(owner)},await key(),new TextEncoder().encode(JSON.stringify(value)));return base64(iv)+'.'+base64(new Uint8Array(encrypted));}
export async function unseal<T>(value:string,owner:string):Promise<T>{const [iv,data]=value.split('.');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64(iv),additionalData:new TextEncoder().encode(owner)},await key(),unbase64(data));return JSON.parse(new TextDecoder().decode(plain));}
export function oauthCookie(value:string,maxAge=600){return `${cookieName}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;}
export type Tokens={access_token:string;refresh_token:string;expires_at:number};
export type Connection={client_id:string;encrypted_tokens:string|null};
export async function connection(owner:string){return db().prepare('SELECT client_id, encrypted_tokens FROM spotify_connections WHERE owner_id = ?').bind(owner).first<Connection>();}
export async function exchange(params:Record<string,string>){const response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new ApiError('Spotify could not connect. Check the Client ID, callback address, and tester access, then try again.',401);return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>;}
export async function accessToken(owner:string){const c=await connection(owner);if(!c?.encrypted_tokens)throw new ApiError('Connect Spotify in settings first.',401);let tokens:Tokens;try{tokens=await unseal<Tokens>(c.encrypted_tokens,owner);}catch{throw new ApiError('Please reconnect Spotify in settings.',401);}if(tokens.expires_at<Date.now()+60000){const fresh=await exchange({grant_type:'refresh_token',refresh_token:tokens.refresh_token,client_id:c.client_id});tokens={access_token:fresh.access_token,refresh_token:fresh.refresh_token||tokens.refresh_token,expires_at:Date.now()+fresh.expires_in*1000};await db().prepare('UPDATE spotify_connections SET encrypted_tokens = ? WHERE owner_id = ?').bind(await seal(tokens,owner),owner).run();}return tokens.access_token;}
export async function spotifyRequest(path:string,token:string,method='GET',data?:unknown){const r=await fetch('https://api.spotify.com/v1'+path,{method,headers:{Authorization:`Bearer ${token}`,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new ApiError(r.status===429?'Spotify is limiting requests. Please wait a little before trying again.':r.status===401?'Please reconnect Spotify in settings.':r.status===403?'Spotify denied access. Check that this account is in your developer app’s tester list.':'Spotify could not finish this request. Please try again.',r.status===429?429:502);return r.status===204?{}:r.json();}
export {matchTrack,type SpotifyTrack} from './track-match';
